In [5]:
import os
import json
import pandas as pd

RAW_DATA = "data/raw"

print("Dataset folders:")
print(os.listdir(RAW_DATA))

Dataset folders:
['archive.zip', 'comp', 'matches', 'players', 'teams']

In [6]:
for root, dirs, files in os.walk(RAW_DATA):
    for file in files:
        if file.endswith(".json"):
            print(os.path.join(root, file))

data/raw\comp\comp_data.json
data/raw\matches\match_data_4653703.json
data/raw\matches\match_data_4653704.json
data/raw\matches\match_data_4653705.json
data/raw\matches\match_data_4653706.json
data/raw\matches\match_data_4653707.json
data/raw\matches\match_data_4653708.json
data/raw\matches\match_data_4653709.json
data/raw\matches\match_data_4653710.json
data/raw\matches\match_data_4653711.json
data/raw\matches\match_data_4653712.json
data/raw\matches\match_data_4653713.json
data/raw\matches\match_data_4653714.json
data/raw\matches\match_data_4653715.json
data/raw\matches\match_data_4653716.json
data/raw\matches\match_data_4653717.json
data/raw\matches\match_data_4653718.json
data/raw\matches\match_data_4653842.json
data/raw\matches\match_data_4653843.json
data/raw\matches\match_data_4653844.json
data/raw\matches\match_data_4653845.json
data/raw\matches\match_data_4653846.json
data/raw\matches\match_data_4653847.json
data/raw\matches\match_data_4653848.json
data/raw\matches\match_data_4653849.json
data/raw\matches\match_data_4653851.json
data/raw\matches\match_data_4653852.json
data/raw\matches\match_data_4653853.json
data/raw\matches\match_data_4653854.json
data/raw\matches\match_data_4653855.json
data/raw\matches\match_data_4653856.json
data/raw\matches\match_data_4653857.json
data/raw\matches\match_data_4653858.json
data/raw\matches\match_data_4667751.json
data/raw\matches\match_data_4667752.json
data/raw\matches\match_data_4667753.json
data/raw\matches\match_data_4667754.json
data/raw\matches\match_data_4667755.json
data/raw\matches\match_data_4667756.json
data/raw\matches\match_data_4667757.json
data/raw\matches\match_data_4667758.json
data/raw\matches\match_data_4667759.json
data/raw\matches\match_data_4667760.json
data/raw\matches\match_data_4667761.json
data/raw\matches\match_data_4667762.json
data/raw\matches\match_data_4667764.json
data/raw\matches\match_data_4667765.json
data/raw\matches\match_data_4667766.json
data/raw\matches\match_data_4667767.json
data/raw\matches\match_data_4667768.json
data/raw\matches\match_data_4667769.json
data/raw\matches\match_data_4667771.json
data/raw\matches\match_data_4667772.json
data/raw\matches\match_data_4667773.json
data/raw\matches\match_data_4667774.json
data/raw\matches\match_data_4667775.json
data/raw\matches\match_data_4667776.json
data/raw\matches\match_data_4667777.json
data/raw\matches\match_data_4667778.json
data/raw\matches\match_data_4667779.json
data/raw\matches\match_data_4667780.json
data/raw\matches\match_data_4667781.json
data/raw\matches\match_data_4667782.json
data/raw\matches\match_data_4667783.json
data/raw\matches\match_data_4667784.json
data/raw\matches\match_data_4667785.json
data/raw\matches\match_data_4667786.json
data/raw\matches\match_data_4667787.json
data/raw\matches\match_data_4667788.json
data/raw\matches\match_data_4667790.json
data/raw\matches\match_data_4667791.json
data/raw\matches\match_data_4667792.json
data/raw\matches\match_data_4667793.json
data/raw\matches\match_data_4667794.json
data/raw\matches\match_data_4667795.json
data/raw\matches\match_data_4667798.json
data/raw\matches\match_data_4667799.json
data/raw\matches\match_data_4667800.json
data/raw\matches\match_data_4667801.json
data/raw\matches\match_data_4667802.json
data/raw\matches\match_data_4667803.json
data/raw\matches\match_data_4667804.json
data/raw\matches\match_data_4667805.json
data/raw\matches\match_data_4667806.json
data/raw\matches\match_data_4667807.json
data/raw\matches\match_data_4667808.json
data/raw\matches\match_data_4667809.json
data/raw\matches\match_data_4667812.json
data/raw\matches\match_data_4667813.json
data/raw\matches\match_data_4667814.json
data/raw\matches\match_data_4667815.json
data/raw\matches\match_data_4667816.json
data/raw\matches\match_data_4667817.json
data/raw\matches\match_data_4667819.json
data/raw\matches\match_data_4667820.json
data/raw\matches\match_data_4667821.json
data/raw\matches\match_data_4667822.json
data/raw\matches\match_data_4667823.json
data/raw\matches\match_data_4667824.json
data/raw\matches\match_data_4667825.json
data/raw\matches\match_data_4667826.json
data/raw\matches\match_data_4667827.json
data/raw\matches\match_data_4667828.json
data/raw\matches\match_data_4667829.json
data/raw\matches\match_data_4667830.json
data/raw\players\team-10106\player_data_1057426.json
data/raw\players\team-10106\player_data_1174844.json
data/raw\players\team-10106\player_data_1179875.json
data/raw\players\team-10106\player_data_1250485.json
data/raw\players\team-10106\player_data_1284492.json
data/raw\players\team-10106\player_data_1300385.json
data/raw\players\team-10106\player_data_1346860.json
data/raw\players\team-10106\player_data_1415104.json
data/raw\players\team-10106\player_data_1515122.json
data/raw\players\team-10106\player_data_1528815.json
data/raw\players\team-10106\player_data_15403.json
data/raw\players\team-10106\player_data_1684401.json
data/raw\players\team-10106\player_data_1726288.json
data/raw\players\team-10106\player_data_304345.json
data/raw\players\team-10106\player_data_388903.json
data/raw\players\team-10106\player_data_466867.json
data/raw\players\team-10106\player_data_541551.json
data/raw\players\team-10106\player_data_639558.json
data/raw\players\team-10106\player_data_653982.json
data/raw\players\team-10106\player_data_660148.json
data/raw\players\team-10106\player_data_725655.json
data/raw\players\team-10106\player_data_797797.json
data/raw\players\team-10106\player_data_840241.json
data/raw\players\team-10106\player_data_857436.json
data/raw\players\team-10106\player_data_857661.json
data/raw\players\team-10106\player_data_958010.json
data/raw\players\team-10155\player_data_1070712.json
data/raw\players\team-10155\player_data_1077684.json
data/raw\players\team-10155\player_data_1186228.json
data/raw\players\team-10155\player_data_1199714.json
data/raw\players\team-10155\player_data_1210893.json
data/raw\players\team-10155\player_data_1215064.json
data/raw\players\team-10155\player_data_1300358.json
data/raw\players\team-10155\player_data_1382000.json
data/raw\players\team-10155\player_data_1413996.json
data/raw\players\team-10155\player_data_163670.json
data/raw\players\team-10155\player_data_173461.json
data/raw\players\team-10155\player_data_239219.json
data/raw\players\team-10155\player_data_251269.json
data/raw\players\team-10155\player_data_31097.json
data/raw\players\team-10155\player_data_383971.json
data/raw\players\team-10155\player_data_446266.json
data/raw\players\team-10155\player_data_557677.json
data/raw\players\team-10155\player_data_557799.json
data/raw\players\team-10155\player_data_616170.json
data/raw\players\team-10155\player_data_641595.json
data/raw\players\team-10155\player_data_643448.json
data/raw\players\team-10155\player_data_709796.json
data/raw\players\team-10155\player_data_831474.json
data/raw\players\team-10155\player_data_873557.json
data/raw\players\team-10155\player_data_950824.json
data/raw\players\team-10155\player_data_959597.json
data/raw\players\team-10255\player_data_1001335.json
data/raw\players\team-10255\player_data_1022128.json
data/raw\players\team-10255\player_data_1179331.json
data/raw\players\team-10255\player_data_1228546.json
data/raw\players\team-10255\player_data_1272436.json
data/raw\players\team-10255\player_data_1291391.json
data/raw\players\team-10255\player_data_1384425.json
data/raw\players\team-10255\player_data_1418549.json
data/raw\players\team-10255\player_data_1426403.json
data/raw\players\team-10255\player_data_1689101.json
data/raw\players\team-10255\player_data_1689371.json
data/raw\players\team-10255\player_data_1708842.json
data/raw\players\team-10255\player_data_292462.json
data/raw\players\team-10255\player_data_505872.json
data/raw\players\team-10255\player_data_513492.json
data/raw\players\team-10255\player_data_532766.json
data/raw\players\team-10255\player_data_533403.json
data/raw\players\team-10255\player_data_546550.json
data/raw\players\team-10255\player_data_560416.json
data/raw\players\team-10255\player_data_653688.json
data/raw\players\team-10255\player_data_660213.json
data/raw\players\team-10255\player_data_839204.json
data/raw\players\team-10255\player_data_849334.json
data/raw\players\team-10255\player_data_906944.json
data/raw\players\team-10255\player_data_971787.json
data/raw\players\team-10255\player_data_979376.json
data/raw\players\team-287981\player_data_1050160.json
data/raw\players\team-287981\player_data_1125997.json
data/raw\players\team-287981\player_data_1180735.json
data/raw\players\team-287981\player_data_1180784.json
data/raw\players\team-287981\player_data_1210947.json
data/raw\players\team-287981\player_data_1240833.json
data/raw\players\team-287981\player_data_1243246.json
data/raw\players\team-287981\player_data_1335315.json
data/raw\players\team-287981\player_data_1439121.json
data/raw\players\team-287981\player_data_150242.json
data/raw\players\team-287981\player_data_183500.json
data/raw\players\team-287981\player_data_289441.json
data/raw\players\team-287981\player_data_352358.json
data/raw\players\team-287981\player_data_380942.json
data/raw\players\team-287981\player_data_389845.json
data/raw\players\team-287981\player_data_467479.json
data/raw\players\team-287981\player_data_614574.json
data/raw\players\team-287981\player_data_643232.json
data/raw\players\team-287981\player_data_671327.json
data/raw\players\team-287981\player_data_708738.json
data/raw\players\team-287981\player_data_751066.json
data/raw\players\team-287981\player_data_794244.json
data/raw\players\team-287981\player_data_873856.json
data/raw\players\team-287981\player_data_875845.json
data/raw\players\team-287981\player_data_924844.json
data/raw\players\team-287981\player_data_938524.json
data/raw\players\team-5796\player_data_1020026.json
data/raw\players\team-5796\player_data_1031656.json
data/raw\players\team-5796\player_data_1032811.json
data/raw\players\team-5796\player_data_1035614.json
data/raw\players\team-5796\player_data_1053963.json
data/raw\players\team-5796\player_data_1070776.json
data/raw\players\team-5796\player_data_1073402.json
data/raw\players\team-5796\player_data_1137909.json
data/raw\players\team-5796\player_data_401095.json
data/raw\players\team-5796\player_data_438647.json
data/raw\players\team-5796\player_data_465614.json
data/raw\players\team-5796\player_data_474589.json
data/raw\players\team-5796\player_data_553476.json
data/raw\players\team-5796\player_data_56829.json
data/raw\players\team-5796\player_data_620618.json
data/raw\players\team-5796\player_data_729093.json
data/raw\players\team-5796\player_data_743533.json
data/raw\players\team-5796\player_data_751198.json
data/raw\players\team-5796\player_data_840184.json
data/raw\players\team-5796\player_data_840212.json
data/raw\players\team-5796\player_data_848027.json
data/raw\players\team-5796\player_data_848034.json
data/raw\players\team-5796\player_data_861661.json
data/raw\players\team-5796\player_data_921253.json
data/raw\players\team-5796\player_data_941660.json
data/raw\players\team-5796\player_data_950561.json
data/raw\players\team-5810\player_data_1023943.json
data/raw\players\team-5810\player_data_1026105.json
data/raw\players\team-5810\player_data_1026135.json
data/raw\players\team-5810\player_data_1055426.json
data/raw\players\team-5810\player_data_1082106.json
data/raw\players\team-5810\player_data_1100258.json
data/raw\players\team-5810\player_data_1216798.json
data/raw\players\team-5810\player_data_1252132.json
data/raw\players\team-5810\player_data_1288119.json
data/raw\players\team-5810\player_data_1338740.json
data/raw\players\team-5810\player_data_1359536.json
data/raw\players\team-5810\player_data_1399943.json
data/raw\players\team-5810\player_data_1415372.json
data/raw\players\team-5810\player_data_1440009.json
data/raw\players\team-5810\player_data_1494508.json
data/raw\players\team-5810\player_data_432605.json
data/raw\players\team-5810\player_data_464919.json
data/raw\players\team-5810\player_data_544312.json
data/raw\players\team-5810\player_data_729506.json
data/raw\players\team-5810\player_data_751202.json
data/raw\players\team-5810\player_data_789598.json
data/raw\players\team-5810\player_data_816223.json
data/raw\players\team-5810\player_data_847629.json
data/raw\players\team-5810\player_data_932308.json
data/raw\players\team-5810\player_data_939569.json
data/raw\players\team-5810\player_data_943428.json
data/raw\players\team-5816\player_data_1028896.json
data/raw\players\team-5816\player_data_1033300.json
data/raw\players\team-5816\player_data_1036253.json
data/raw\players\team-5816\player_data_1059129.json
data/raw\players\team-5816\player_data_1179369.json
data/raw\players\team-5816\player_data_1195369.json
data/raw\players\team-5816\player_data_1202924.json
data/raw\players\team-5816\player_data_1213678.json
data/raw\players\team-5816\player_data_1247001.json
data/raw\players\team-5816\player_data_1312681.json
data/raw\players\team-5816\player_data_1350517.json
data/raw\players\team-5816\player_data_1554109.json
data/raw\players\team-5816\player_data_1554110.json
data/raw\players\team-5816\player_data_1642793.json
data/raw\players\team-5816\player_data_1823348.json
data/raw\players\team-5816\player_data_1902793.json
data/raw\players\team-5816\player_data_546201.json
data/raw\players\team-5816\player_data_546203.json
data/raw\players\team-5816\player_data_600844.json
data/raw\players\team-5816\player_data_674520.json
data/raw\players\team-5816\player_data_734654.json
data/raw\players\team-5816\player_data_813055.json
data/raw\players\team-5816\player_data_847766.json
data/raw\players\team-5816\player_data_852168.json
data/raw\players\team-5816\player_data_915790.json
data/raw\players\team-5819\player_data_1042511.json
data/raw\players\team-5819\player_data_1092563.json
data/raw\players\team-5819\player_data_1113688.json
data/raw\players\team-5819\player_data_1132570.json
data/raw\players\team-5819\player_data_1132572.json
data/raw\players\team-5819\player_data_1138592.json
data/raw\players\team-5819\player_data_1162514.json
data/raw\players\team-5819\player_data_1199113.json
data/raw\players\team-5819\player_data_1224691.json
data/raw\players\team-5819\player_data_1235623.json
data/raw\players\team-5819\player_data_1333336.json
data/raw\players\team-5819\player_data_1420369.json
data/raw\players\team-5819\player_data_1478238.json
data/raw\players\team-5819\player_data_1554123.json
data/raw\players\team-5819\player_data_1606279.json
data/raw\players\team-5819\player_data_1642810.json
data/raw\players\team-5819\player_data_1642820.json
data/raw\players\team-5819\player_data_320139.json
data/raw\players\team-5819\player_data_502481.json
data/raw\players\team-5819\player_data_533495.json
data/raw\players\team-5819\player_data_578761.json
data/raw\players\team-5819\player_data_674332.json
data/raw\players\team-5819\player_data_858340.json
data/raw\players\team-5819\player_data_926484.json
data/raw\players\team-5819\player_data_941579.json
data/raw\players\team-5819\player_data_942834.json
data/raw\players\team-5820\player_data_1013276.json
data/raw\players\team-5820\player_data_1034995.json
data/raw\players\team-5820\player_data_1053731.json
data/raw\players\team-5820\player_data_1053736.json
data/raw\players\team-5820\player_data_115025.json
data/raw\players\team-5820\player_data_1209597.json
data/raw\players\team-5820\player_data_1257745.json
data/raw\players\team-5820\player_data_1272118.json
data/raw\players\team-5820\player_data_128949.json
data/raw\players\team-5820\player_data_1325761.json
data/raw\players\team-5820\player_data_1460327.json
data/raw\players\team-5820\player_data_1565865.json
data/raw\players\team-5820\player_data_169719.json
data/raw\players\team-5820\player_data_315201.json
data/raw\players\team-5820\player_data_324305.json
data/raw\players\team-5820\player_data_496356.json
data/raw\players\team-5820\player_data_519240.json
data/raw\players\team-5820\player_data_676431.json
data/raw\players\team-5820\player_data_724531.json
data/raw\players\team-5820\player_data_825593.json
data/raw\players\team-5820\player_data_848317.json
data/raw\players\team-5820\player_data_848345.json
data/raw\players\team-5820\player_data_848352.json
data/raw\players\team-5820\player_data_919671.json
data/raw\players\team-5820\player_data_96488.json
data/raw\players\team-5888\player_data_1054027.json
data/raw\players\team-5888\player_data_1165477.json
data/raw\players\team-5888\player_data_1175733.json
data/raw\players\team-5888\player_data_1205410.json
data/raw\players\team-5888\player_data_1241301.json
data/raw\players\team-5888\player_data_1241302.json
data/raw\players\team-5888\player_data_1309634.json
data/raw\players\team-5888\player_data_1441786.json
data/raw\players\team-5888\player_data_1460591.json
data/raw\players\team-5888\player_data_1524518.json
data/raw\players\team-5888\player_data_164062.json
data/raw\players\team-5888\player_data_172615.json
data/raw\players\team-5888\player_data_230134.json
data/raw\players\team-5888\player_data_302912.json
data/raw\players\team-5888\player_data_422149.json
data/raw\players\team-5888\player_data_444000.json
data/raw\players\team-5888\player_data_496648.json
data/raw\players\team-5888\player_data_665167.json
data/raw\players\team-5888\player_data_671326.json
data/raw\players\team-5888\player_data_680905.json
data/raw\players\team-5888\player_data_785716.json
data/raw\players\team-5888\player_data_798069.json
data/raw\players\team-5888\player_data_865144.json
data/raw\players\team-5888\player_data_873832.json
data/raw\players\team-5888\player_data_890503.json
data/raw\players\team-5888\player_data_922877.json
data/raw\players\team-5902\player_data_1053982.json
data/raw\players\team-5902\player_data_1053987.json
data/raw\players\team-5902\player_data_117539.json
data/raw\players\team-5902\player_data_1195865.json
data/raw\players\team-5902\player_data_1210913.json
data/raw\players\team-5902\player_data_1213141.json
data/raw\players\team-5902\player_data_1432180.json
data/raw\players\team-5902\player_data_149583.json
data/raw\players\team-5902\player_data_1553870.json
data/raw\players\team-5902\player_data_1642780.json
data/raw\players\team-5902\player_data_1648351.json
data/raw\players\team-5902\player_data_1839745.json
data/raw\players\team-5902\player_data_264096.json
data/raw\players\team-5902\player_data_308909.json
data/raw\players\team-5902\player_data_308921.json
data/raw\players\team-5902\player_data_309153.json
data/raw\players\team-5902\player_data_365245.json
data/raw\players\team-5902\player_data_431151.json
data/raw\players\team-5902\player_data_613792.json
data/raw\players\team-5902\player_data_615414.json
data/raw\players\team-5902\player_data_644014.json
data/raw\players\team-5902\player_data_644017.json
data/raw\players\team-5902\player_data_734637.json
data/raw\players\team-5902\player_data_898424.json
data/raw\players\team-5902\player_data_922387.json
data/raw\players\team-5902\player_data_937414.json
data/raw\players\team-5922\player_data_1017520.json
data/raw\players\team-5922\player_data_1054138.json
data/raw\players\team-5922\player_data_1137803.json
data/raw\players\team-5922\player_data_1223132.json
data/raw\players\team-5922\player_data_1330683.json
data/raw\players\team-5922\player_data_1404414.json
data/raw\players\team-5922\player_data_1454648.json
data/raw\players\team-5922\player_data_183088.json
data/raw\players\team-5922\player_data_206088.json
data/raw\players\team-5922\player_data_308131.json
data/raw\players\team-5922\player_data_312159.json
data/raw\players\team-5922\player_data_501847.json
data/raw\players\team-5922\player_data_503710.json
data/raw\players\team-5922\player_data_526710.json
data/raw\players\team-5922\player_data_531913.json
data/raw\players\team-5922\player_data_574077.json
data/raw\players\team-5922\player_data_643635.json
data/raw\players\team-5922\player_data_643638.json

In [7]:
for folder in ["comp", "matches", "players", "teams"]:
    path = os.path.join(RAW_DATA, folder)
    files = [
        f for f in os.listdir(path)
        if os.path.isfile(os.path.join(path, f))
    ]
    print(f"{folder}: {len(files)} files")

comp: 4 files
matches: 104 files
players: 0 files
teams: 48 files

In [8]:
import os

comp_path = "data/raw/comp"

print(os.listdir(comp_path))

['comp_data.json', 'fixtures_lookup.csv', 'players_lookup.csv', 'teams_lookup.csv']

In [9]:
import pandas as pd

player_lookup_path = "data/raw/comp/players_lookup.csv"

players = pd.read_csv(player_lookup_path)

players.head()

,player_id,player_name,country,country_id,birth_date_utc,primary_position,club_id,club_name,height_cm,preferred_foot,transfer_value_eur
0,1057426,Armin Gigovic,Bosnia and Herzegovina,10106,2002-04-06,defensive midfielder,10192.0,Young Boys,187.0,right,1950982.0
1,1174844,Jovo Lukic,Bosnia and Herzegovina,10106,1998-11-28,striker,89022.0,Universitatea Cluj,190.0,left,959713.0
2,1179875,Ivan Basic,Bosnia and Herzegovina,10106,2002-04-30,central midfielder,166865.0,FC Astana,178.0,left,724785.0
3,1250485,Tarik Muharemovic,Bosnia and Herzegovina,10106,2003-02-28,center back,8463.0,Leeds United,187.0,left,17870981.0
4,1284492,Samed Bazdar,Bosnia and Herzegovina,10106,2004-01-31,striker,8394.0,Real Zaragoza,186.0,right,1251348.0

In [10]:
players.columns.tolist()

['player_id',
 'player_name',
 'country',
 'country_id',
 'birth_date_utc',
 'primary_position',
 'club_id',
 'club_name',
 'height_cm',
 'preferred_foot',
 'transfer_value_eur']

In [12]:
print("Total rows:", len(players))
print("Unique player IDs:", players["player_id"].nunique())
print("Unique player names:", players["player_name"].nunique())

Total rows: 1243
Unique player IDs: 1243
Unique player names: 1242

In [13]:
print("Duplicate player IDs:", players["player_id"].duplicated().sum())

Duplicate player IDs: 0

In [14]:
players.isnull().sum()

player_id              0
player_name            0
country                0
country_id             0
birth_date_utc         0
primary_position       0
club_id               21
club_name             21
height_cm              2
preferred_foot         0
transfer_value_eur    57
dtype: int64

In [15]:
players[players["club_name"].isna()]

,player_id,player_name,country,country_id,birth_date_utc,primary_position,club_id,club_name,height_cm,preferred_foot,transfer_value_eur
10,15403,Edin Dzeko,Bosnia and Herzegovina,10106,1986-03-17,striker,NaN,NaN,193.0,both,990541.0
64,292462,Mohamed Salah,Egypt,10255,1992-06-15,right winger,NaN,NaN,175.0,left,35103349.0
93,467479,Riechedly Bazoer,Curacao,287981,1996-10-12,center back,NaN,NaN,184.0,right,1152541.0
313,1181438,Martin Expérience,Haiti,5934,1999-03-09,left wing-back,NaN,NaN,178.0,left,217557.0
367,1178629,Jayden Adams,South Africa,6316,2001-05-05,defensive midfielder,NaN,NaN,175.0,right,316800.0
534,195927,Enner Valencia,Ecuador,6707,1989-11-04,striker,NaN,NaN,177.0,right,1001139.0
686,1806615,Benjamin Asare,Ghana,6714,1992-07-13,keeper,NaN,NaN,188.0,right,NaN
694,776591,Abdul Mumin,Ghana,6714,1998-06-06,defender,NaN,NaN,188.0,right,2110965.0
713,664444,Takehiro Tomiyasu,Japan,6715,1998-11-05,center back,NaN,NaN,187.0,right,4456133.0
738,185644,Mathew Ryan,Australia,6716,1992-04-08,keeper,NaN,NaN,184.0,right,1514941.0
770,705484,Eray Cömert,Switzerland,6717,1998-02-04,center back,NaN,NaN,183.0,right,1520685.0
937,121633,David Alaba,Austria,8255,1992-06-24,center back,NaN,NaN,180.0,left,1720863.0
947,617044,Florian Grillitsch,Austria,8255,1995-08-07,central midfielder,NaN,NaN,187.0,right,1149729.0
948,620027,Xaver Schlager,Austria,8255,1997-09-28,central midfielder,NaN,NaN,174.0,left,6336970.0
966,208494,Casemiro,Brazil,8256,1992-02-23,defensive midfielder,NaN,NaN,185.0,right,5739627.0
1027,39591,Axel Witsel,Belgium,8263,1989-01-12,defensive midfielder,NaN,NaN,186.0,right,1154326.0
1071,263653,John Stones,England,8491,1994-05-28,center back,NaN,NaN,188.0,right,11804553.0
1105,73409,Ørjan Nyland,Norway,8492,1990-09-10,keeper,NaN,NaN,192.0,right,482586.0
1147,32562,Craig Gordon,Scotland,8498,1982-12-31,keeper,NaN,NaN,193.0,left,254417.0
1206,343748,Leon Goretzka,Germany,8570,1995-02-06,defensive midfielder,NaN,NaN,189.0,right,11719071.0
1225,1477513,Jakhongir Urozov,Uzbekistan,8700,2004-01-18,center back,NaN,NaN,190.0,left,653889.0

In [16]:
players[players["height_cm"].isna()]

,player_id,player_name,country,country_id,birth_date_utc,primary_position,club_id,club_name,height_cm,preferred_foot,transfer_value_eur
1168,1135782,Taha Abdi Ali,Sweden,8520,1998-07-01,right midfielder,8619.0,PAOK Thessaloniki,NaN,right,625013.0
1172,1272349,Elliot Stroud,Sweden,8520,2002-06-22,left midfielder,8127.0,Mjällby,NaN,left,2088915.0

In [17]:
players[players["transfer_value_eur"].isna()][
    ["player_id", "player_name", "country", "club_name"]
]

,player_id,player_name,country,club_name
12,1726288,Mladen Jurkas,Bosnia and Herzegovina,Borac Banja Luka
55,1228546,Mostafa Ahmed Shobeir,Egypt,Al Ahly SC
60,1426403,Mostafa Ziko,Egypt,Pyramids FC
63,1708842,Hamza Abdelkarim,Egypt,Barca Atletic
158,1036253,Noor Al Rawabdeh,Jordan,Selangor
159,1059129,Mohammad Abuzraiq,Jordan,Raja Casablanca
160,1179369,Saed Al-Rosan,Jordan,Ethad All Ramtha
163,1213678,Amer Jamous,Jordan,Al Zawraa
165,1312681,Abdallah Nasib,Jordan,Al-Hussein SC
167,1554109,Husam Abu Dahab,Jordan,Al-Faisaly
168,1554110,Nour Bani Attiah,Jordan,Al-Faisaly
170,1823348,Odeh Fakhouri,Jordan,Pyramids FC
171,1902793,Mohammad Abu Ghoush,Jordan,Shabab Al Ordon Al Quadisiya
172,546201,Ehsan Haddad,Jordan,Al-Hussein SC
173,546203,Rajaei Ayed,Jordan,Al-Hussein SC
174,600844,Mohammad Al-Daoud,Jordan,Al-Salt
175,674520,Mahmoud Al Mardi,Jordan,Al-Hussein SC
176,734654,Yazeed Abulaila,Jordan,Al-Hussein SC
178,847766,Saleem Obaid,Jordan,Al-Hussein SC
180,915790,Abdullah Al Fakhouri,Jordan,Al-Wehdat
184,1132570,Ahmed Basil Fadhil,Iraq,Al Shorta
185,1132572,Ali Yousif,Iraq,Al Talaba
191,1333336,Manaf Younis,Iraq,Al Shorta
194,1554123,Mustafa Saadoun,Iraq,Al Shorta
195,1606279,Akam Hashem,Iraq,Al Zawraa
196,1642810,Ahmed Maknzi,Iraq,Al-Karma
197,1642820,Zaid Ismael,Iraq,Al Talaba
200,533495,Fahad Talib,Iraq,Al Talaba
201,578761,Jalal Hassan,Iraq,Al Zawraa
206,942834,Ibrahim Bayesh,Iraq,Al-Dhafra
235,1205410,Yannick Semedo,Cape Verde,Farense
264,1432180,Ayoub Al Oui,Qatar,Al-Gharafa
268,1648351,Tahsin Mohammed,Qatar,Al-Duhail SC
280,734637,Pedro Miguel,Qatar,Al-Sadd
288,1330683,César Samudio,Panama,CD Marathon
311,1079194,Don Deedson Louicius,Haiti,FC Dallas
322,1447452,Olivier Pierre,Haiti,Real Hope FA
335,899023,Josué Duverger,Haiti,FC Cosmos Koblenz
391,1116034,Oussama Benbot,Algeria,USM Alger
402,1362385,Achref Abada,Algeria,USM Alger
532,1477417,Denil Castillo,Ecuador,FC Midtjylland
629,1729681,Danial Eiri,Iran,Zob Ahan
686,1806615,Benjamin Asare,Ghana,NaN
810,1553105,Víctor Muñoz,Spain,Liverpool
881,1095207,Ayman Yahya,Saudi Arabia,Al Nassr FC
885,1232530,Jehad Thakri,Saudi Arabia,Al Qadsiah
896,697618,Alaa Hajji,Saudi Arabia,Neom SC
907,1053477,Tae-Hyeon Kim,South Korea,Kashima Antlers
916,1386482,Jun-Ho Bae,South Korea,Stoke City
987,1353421,Andrés Gómez,Colombia,Vasco da Gama
1044,361717,Rui Silva,Portugal,Sporting CP
1123,1764021,Hugo Sochurek,Czechia,Sparta Prague
1143,1676985,Tyler Fletcher,Scotland,Manchester United U21
1217,1029597,Avazbek Ulasmaliev,Uzbekistan,AGMK
1222,1294120,Abdulla Abdullaev,Uzbekistan,Dibba Al Fujairah
1227,1898281,Bekhruz Karimov,Uzbekistan,PFC Surkhon Termez
1242,940778,Khoziakbar Alidzhanov,Uzbekistan,Pakhtakor Tashkent

In [23]:
import pandas as pd
import numpy as np

In [24]:
players_clean = players.copy()

# Remove whitespace from text columns
text_columns = [
    "player_name",
    "country",
    "primary_position",
    "club_name",
    "preferred_foot"
]

for col in text_columns:
    players_clean[col] = players_clean[col].str.strip()

# Convert date
players_clean["birth_date_utc"] = pd.to_datetime(
    players_clean["birth_date_utc"],
    errors="coerce"
)

# Convert numeric columns
players_clean["height_cm"] = pd.to_numeric(
    players_clean["height_cm"],
    errors="coerce"
)

players_clean["transfer_value_eur"] = pd.to_numeric(
    players_clean["transfer_value_eur"],
    errors="coerce"
)

# Keep missing club names as Unknown
players_clean["club_name"] = players_clean["club_name"].fillna("Unknown")

# Remove duplicate player IDs
players_clean = players_clean.drop_duplicates(
    subset="player_id"
)

In [25]:
print("Original rows:", len(players))
print("Cleaned rows:", len(players_clean))

print("\nMissing values:")
print(players_clean.isnull().sum())

Original rows: 1243
Cleaned rows: 1243

Missing values:
player_id              0
player_name            0
country                0
country_id             0
birth_date_utc         0
primary_position       0
club_id               21
club_name              0
height_cm              2
preferred_foot         0
transfer_value_eur    57
dtype: int64

In [26]:
players_clean.head()

,player_id,player_name,country,country_id,birth_date_utc,primary_position,club_id,club_name,height_cm,preferred_foot,transfer_value_eur
0,1057426,Armin Gigovic,Bosnia and Herzegovina,10106,2002-04-06,defensive midfielder,10192.0,Young Boys,187.0,right,1950982.0
1,1174844,Jovo Lukic,Bosnia and Herzegovina,10106,1998-11-28,striker,89022.0,Universitatea Cluj,190.0,left,959713.0
2,1179875,Ivan Basic,Bosnia and Herzegovina,10106,2002-04-30,central midfielder,166865.0,FC Astana,178.0,left,724785.0
3,1250485,Tarik Muharemovic,Bosnia and Herzegovina,10106,2003-02-28,center back,8463.0,Leeds United,187.0,left,17870981.0
4,1284492,Samed Bazdar,Bosnia and Herzegovina,10106,2004-01-31,striker,8394.0,Real Zaragoza,186.0,right,1251348.0

In [27]:
import os

os.makedirs("data/processed", exist_ok=True)

players_clean.to_csv(
    "data/processed/players_clean.csv",
    index=False
)

In [28]:
#Load teams_lookup.csv

team_lookup_path = "data/raw/comp/teams_lookup.csv"

teams = pd.read_csv(team_lookup_path)

print("Rows:", len(teams))
print("Columns:")
print(teams.columns.tolist())

teams.head()

Rows: 48
Columns:
['team_id', 'team', 'group_id', 'group', 'fifa_rank', 'rank_last_updated', 'current_head_coach', 'head_coach_id']

,team_id,team,group_id,group,fifa_rank,rank_last_updated,current_head_coach,head_coach_id
0,6710,Mexico,894790,Group A,14,2026-06-11,Javier Aguirre,78642.0
1,6316,South Africa,894790,Group A,60,2026-06-11,Hugo Broos,179919.0
2,7804,South Korea,894790,Group A,25,2026-06-11,NaN,NaN
3,8496,Czechia,894790,Group A,40,2026-06-11,NaN,NaN
4,6717,Switzerland,894791,Group B,19,2026-06-11,Murat Yakin,34053.0

In [29]:
teams.isnull().sum()

team_id               0
team                  0
group_id              0
group                 0
fifa_rank             0
rank_last_updated     0
current_head_coach    6
head_coach_id         6
dtype: int64

In [30]:
#cleaning it
teams_clean = teams.copy()

# Remove extra spaces from text columns
for col in teams_clean.select_dtypes(include="object").columns:
    teams_clean[col] = teams_clean[col].str.strip()

# Remove duplicate team IDs
teams_clean = teams_clean.drop_duplicates(
    subset="team_id"
)

print("Original rows:", len(teams))
print("Cleaned rows:", len(teams_clean))

Original rows: 48
Cleaned rows: 48

C:\Users\A C E R\AppData\Local\Temp\ipykernel_11328\1045226913.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in teams_clean.select_dtypes(include="object").columns:

In [31]:
teams.dtypes

team_id                 int64
team                      str
group_id                int64
group                     str
fifa_rank               int64
rank_last_updated         str
current_head_coach        str
head_coach_id         float64
dtype: object

In [33]:
print(teams_clean.columns.tolist())

['team_id', 'team', 'group_id', 'group', 'fifa_rank', 'rank_last_updated', 'current_head_coach', 'head_coach_id']

In [34]:
# Make a copy
teams_clean = teams.copy()

# Clean text columns
text_columns = [
    "team",
    "group",
    "rank_last_updated",
    "current_head_coach"
]

for col in text_columns:
    teams_clean[col] = teams_clean[col].str.strip()

# Convert date
teams_clean["rank_last_updated"] = pd.to_datetime(
    teams_clean["rank_last_updated"],
    errors="coerce"
)

# Convert coach ID
teams_clean["head_coach_id"] = teams_clean["head_coach_id"].astype("Int64")

# Remove duplicate teams
teams_clean = teams_clean.drop_duplicates(
    subset=["team_id"]
)

In [35]:
print("Original rows:", len(teams))
print("Cleaned rows:", len(teams_clean))
print("Unique teams:", teams_clean["team_id"].nunique())

Original rows: 48
Cleaned rows: 48
Unique teams: 48

In [36]:
teams_clean.isnull().sum()

team_id               0
team                  0
group_id              0
group                 0
fifa_rank             0
rank_last_updated     0
current_head_coach    6
head_coach_id         6
dtype: int64

In [37]:
import os

os.makedirs("data/processed", exist_ok=True)

teams_clean.to_csv(
    "data/processed/teams_clean.csv",
    index=False
)

print("Teams data cleaned and saved.")

Teams data cleaned and saved.

In [38]:
#Loadding fixtures
fixtures_path = "data/raw/comp/fixtures_lookup.csv"

fixtures = pd.read_csv(fixtures_path)

print("Rows:", len(fixtures))
print("Columns:")
print(fixtures.columns.tolist())

Rows: 104
Columns:
['match_id', 'round_num', 'phase', 'team_1_id', 'team_1', 'team_2_id', 'team_2', 'match_date_utc', 'start_time_utc', 'is_started', 'is_finished', 'is_cancelled', 'is_awarded', 'status', 'venue', 'host_nation', 'latitude', 'longitude']

In [39]:
fixtures.head()

,match_id,round_num,phase,team_1_id,team_1,team_2_id,team_2,match_date_utc,start_time_utc,is_started,is_finished,is_cancelled,is_awarded,status,venue,host_nation,latitude,longitude
0,4667751,1,group phase,6710,Mexico,6316,South Africa,2026-06-11,19:00:00.000000000,True,True,False,False,full-time,Mexico City Stadium,Mexico,19.302825,-99.150388
1,4667752,1,group phase,7804,South Korea,8496,Czechia,2026-06-12,02:00:00.000000000,True,True,False,False,full-time,Guadalajara Stadium,Mexico,20.681775,-103.462629
2,4667757,1,group phase,5810,Canada,10106,Bosnia and Herzegovina,2026-06-12,19:00:00.000000000,True,True,False,False,full-time,Toronto Stadium,Canada,43.633206,-79.418557
3,4667771,1,group phase,6713,USA,6724,Paraguay,2026-06-13,01:00:00.000000000,True,True,False,False,full-time,Los Angeles Stadium,United States,33.953425,-118.338948
4,4667758,1,group phase,5902,Qatar,6717,Switzerland,2026-06-13,19:00:00.000000000,True,True,False,False,full-time,San Francisco Bay Area Stadium,United States,37.403228,-121.969776

In [40]:
fixtures.isnull().sum()

match_id          0
round_num         0
phase             0
team_1_id         0
team_1            0
team_2_id         0
team_2            0
match_date_utc    0
start_time_utc    0
is_started        0
is_finished       0
is_cancelled      0
is_awarded        0
status            0
venue             0
host_nation       0
latitude          0
longitude         0
dtype: int64

In [41]:
fixtures.dtypes

match_id            int64
round_num           int64
phase                 str
team_1_id           int64
team_1                str
team_2_id           int64
team_2                str
match_date_utc        str
start_time_utc        str
is_started           bool
is_finished          bool
is_cancelled         bool
is_awarded           bool
status                str
venue                 str
host_nation           str
latitude          float64
longitude         float64
dtype: object

In [42]:
#cleaning fixtures.csv
fixtures_clean = fixtures.copy()

# Clean text columns
text_columns = [
    "phase",
    "team_1",
    "team_2",
    "status",
    "venue",
    "host_nation"
]

for col in text_columns:
    fixtures_clean[col] = fixtures_clean[col].str.strip()

# Convert date/time columns
fixtures_clean["match_date_utc"] = pd.to_datetime(
    fixtures_clean["match_date_utc"],
    errors="coerce",
    utc=True
)

fixtures_clean["start_time_utc"] = pd.to_datetime(
    fixtures_clean["start_time_utc"],
    errors="coerce",
    utc=True
)

# Ensure ID columns are integers
fixtures_clean["match_id"] = pd.to_numeric(
    fixtures_clean["match_id"],
    errors="coerce"
).astype("Int64")

fixtures_clean["team_1_id"] = pd.to_numeric(
    fixtures_clean["team_1_id"],
    errors="coerce"
).astype("Int64")

fixtures_clean["team_2_id"] = pd.to_numeric(
    fixtures_clean["team_2_id"],
    errors="coerce"
).astype("Int64")

# Remove duplicate matches
fixtures_clean = fixtures_clean.drop_duplicates(
    subset=["match_id"]
)

print("Original rows:", len(fixtures))
print("Cleaned rows:", len(fixtures_clean))

Original rows: 104
Cleaned rows: 104

C:\Users\A C E R\AppData\Local\Temp\ipykernel_11328\107343830.py:24: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fixtures_clean["start_time_utc"] = pd.to_datetime(

In [43]:
fixtures_clean.isnull().sum()

match_id          0
round_num         0
phase             0
team_1_id         0
team_1            0
team_2_id         0
team_2            0
match_date_utc    0
start_time_utc    0
is_started        0
is_finished       0
is_cancelled      0
is_awarded        0
status            0
venue             0
host_nation       0
latitude          0
longitude         0
dtype: int64

In [44]:
print(
    "Duplicate match IDs:",
    fixtures_clean["match_id"].duplicated().sum()
)

Duplicate match IDs: 0

In [45]:
fixtures_clean["status"].value_counts(dropna=False)

status
full-time           95
after extra time     5
after penalties      4
Name: count, dtype: int64

In [46]:
fixtures_clean[
    ["match_id", "team_1", "team_2", "match_date_utc", "status"]
].head(10)

,match_id,team_1,team_2,match_date_utc,status
0,4667751,Mexico,South Africa,2026-06-11 00:00:00+00:00,full-time
1,4667752,South Korea,Czechia,2026-06-12 00:00:00+00:00,full-time
2,4667757,Canada,Bosnia and Herzegovina,2026-06-12 00:00:00+00:00,full-time
3,4667771,USA,Paraguay,2026-06-13 00:00:00+00:00,full-time
4,4667758,Qatar,Switzerland,2026-06-13 00:00:00+00:00,full-time
5,4667764,Brazil,Morocco,2026-06-13 00:00:00+00:00,full-time
6,4667765,Haiti,Scotland,2026-06-14 00:00:00+00:00,full-time
7,4667772,Australia,Turkiye,2026-06-14 00:00:00+00:00,full-time
8,4667777,Germany,Curacao,2026-06-14 00:00:00+00:00,full-time
9,4667783,Netherlands,Japan,2026-06-14 00:00:00+00:00,full-time

In [47]:
fixtures_clean.to_csv(
    "data/processed/fixtures_clean.csv",
    index=False
)

print("Fixtures cleaned and saved!")

Fixtures cleaned and saved!

In [48]:
#exploring match data

matches_path = "data/raw/matches"

match_files = [
    f for f in os.listdir(matches_path)
    if f.endswith(".json")
]

print("Total match files:", len(match_files))
print("First match file:", match_files[0])

Total match files: 104
First match file: match_data_4653703.json

In [49]:
#loading first match
first_match_path = os.path.join(
    matches_path,
    match_files[0]
)

with open(first_match_path, "r", encoding="utf-8") as f:
    match_data = json.load(f)

print(type(match_data))
print(match_data.keys())

<class 'dict'>
dict_keys(['general', 'header', 'nav', 'ongoing', 'hasPendingVAR', 'content', 'seo'])

In [50]:
for key, value in match_data.items():
    print(
        key,
        "->",
        type(value),
        f"({len(value)} items)" if isinstance(value, (dict, list)) else ""
    )

general -> <class 'dict'> (17 items)
header -> <class 'dict'> (3 items)
nav -> <class 'list'> (5 items)
ongoing -> <class 'bool'>
hasPendingVAR -> <class 'bool'>
content -> <class 'dict'> (16 items)
seo -> <class 'dict'> (4 items)

In [51]:
print(json.dumps(match_data, indent=2)[:5000])

{
  "general": {
    "matchId": "4653703",
    "matchName": "Germany-vs-Paraguay_Mon, Jun 29, 2026, 20:30 UTC",
    "matchRound": "1/16",
    "teamColors": {
      "darkMode": {
        "home": "#ffffff",
        "away": "#EE3F2D"
      },
      "lightMode": {
        "home": "#464646",
        "away": "#EE3F2D"
      },
      "fontDarkMode": {
        "home": "rgba(29, 29, 29, 1.0)",
        "away": "rgba(255, 255, 255, 1.0)"
      },
      "fontLightMode": {
        "home": "rgba(255, 255, 255, 1.0)",
        "away": "rgba(255, 255, 255, 1.0)"
      }
    },
    "leagueId": 894789,
    "leagueName": "World Cup",
    "leagueRoundName": "1/16",
    "parentLeagueId": 77,
    "countryCode": "INT",
    "homeTeam": {
      "name": "Germany",
      "id": 8570
    },
    "awayTeam": {
      "name": "Paraguay",
      "id": 6724
    },
    "coverageLevel": "xG",
    "matchTimeUTC": "Mon, Jun 29, 2026, 20:30 UTC",
    "matchTimeUTCDate": "2026-06-29T20:30:00.000Z",
    "started": true,
    "finished": true,
    "gender": "male"
  },
  "header": {
    "teams": [
      {
        "name": "Germany",
        "id": 8570,
        "score": 1,
        "imageUrl": "https://images.fotmob.com/image_resources/logo/teamlogo/8570_small.png",
        "pageUrl": "/teams/8570/overview/germany",
        "fifaRank": 10
      },
      {
        "name": "Paraguay",
        "id": 6724,
        "score": 1,
        "imageUrl": "https://images.fotmob.com/image_resources/logo/teamlogo/6724_small.png",
        "pageUrl": "/teams/6724/overview/paraguay",
        "fifaRank": 41
      }
    ],
    "status": {
      "utcTime": "2026-06-29T20:30:00.000Z",
      "numberOfHomeRedCards": 0,
      "numberOfAwayRedCards": 0,
      "halfs": {
        "firstHalfStarted": "29.06.2026 22:30:17",
        "firstHalfEnded": "29.06.2026 23:20:42",
        "secondHalfStarted": "29.06.2026 23:38:11",
        "secondHalfEnded": "30.06.2026 00:28:29",
        "firstExtraHalfStarted": "30.06.2026 00:33:21",
        "secondExtraHalfStarted": "30.06.2026 00:55:22",
        "gameEnded": "30.06.2026 01:28:33"
      },
      "finished": true,
      "started": true,
      "cancelled": false,
      "awarded": false,
      "scoreStr": "1 - 1",
      "reason": {
        "short": "Pen",
        "shortKey": "penalties_short",
        "long": "Pen 3 - 4",
        "longKey": "afterpenalties",
        "penalties": [
          3,
          4
        ]
      },
      "whoLostOnPenalties": "Germany",
      "whoLostOnAggregated": ""
    },
    "events": {
      "homeTeamGoals": {
        "Havertz": [
          {
            "reactKey": "1421909054Goal749736undefinedtrue",
            "timeStr": 54,
            "type": "Goal",
            "time": 54,
            "overloadTime": null,
            "eventId": 14219090,
            "player": {
              "id": 749736,
              "name": "Kai Havertz",
              "profileUrl": "/players/749736/kai-havertz"
            },
            "homeScore": 0,
            "awayScore": 1,
            "profileUrl": "/players/749736/kai-havertz",
            "overloadTimeStr": false,
            "isHome": true,
            "ownGoal": null,
            "goalDescription": "Header",
            "goalDescriptionKey": "header",
            "suffix": null,
            "suffixKey": null,
            "isPenaltyShootoutEvent": false,
            "nameStr": "Kai Havertz",
            "firstName": "Kai",
            "lastName": "Havertz",
            "fullName": "Kai Havertz",
            "playerId": 749736,
            "newScore": [
              1,
              1
            ],
            "penShootoutScore": null,
            "shotmapEvent": {
              "id": 2945819977,
              "eventType": "Goal",
              "teamId": 8570,
              "playerId": 749736,
              "playerName": "Kai Havertz",
              "x": 94.38596491070001,
              "y": 35.6775,
              "min": 54,
              "minAdded": null,
              "isBlocked": false,
              "isOnTarget": true,
              "blockedX": null,
              "blockedY": null,
              "goalCrossedY": 31.026249999999997,
              "goalCrossedZ": 0.6485263126,
              "expectedGoals": 0.03393787518143654,
              "expectedGoalsOnTarget": 0.34467142820358276,
              "shotType": "Header",
              "situation": "RegularPlay",
              "period": "SecondHalf",
              "isOwnGoal": false,
              "onGoalShot": {
                "x": 1.7867063492063497,
                "y": 0.17156780756613757,
                "zoomRatio": 1
              },
              "isSavedOffLine": false,
              "isFromInsideBox": true,
              "keeperId": 1683391,
              "firstName": "Kai",
              "lastName": "Havertz",
              "fullName": "Kai Havertz",
              "teamColor": "#464646"
            },
            "assistStr": "assist by Florian Wirtz",
            "assistProfileUrl": "/players/1152455/florian-w

In [52]:
import os
import json
import pandas as pd

matches_path = "data/raw/matches"

match_rows = []

for filename in os.listdir(matches_path):
    if not filename.endswith(".json"):
        continue

    filepath = os.path.join(matches_path, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    general = data.get("general", {})
    header = data.get("header", {})
    teams_data = header.get("teams", [])
    status = header.get("status", {})

    home_team = teams_data[0] if len(teams_data) > 0 else {}
    away_team = teams_data[1] if len(teams_data) > 1 else {}

    match_rows.append({
        "match_id": general.get("matchId"),
        "match_name": general.get("matchName"),
        "round": general.get("matchRound"),
        
        "home_team_id": home_team.get("id"),
        "home_team": home_team.get("name"),
        "home_score": home_team.get("score"),
        "home_fifa_rank": home_team.get("fifaRank"),
        
        "away_team_id": away_team.get("id"),
        "away_team": away_team.get("name"),
        "away_score": away_team.get("score"),
        "away_fifa_rank": away_team.get("fifaRank"),
        
        "match_time_utc": general.get("matchTimeUTCDate"),
        "started": general.get("started"),
        "finished": general.get("finished"),
        "cancelled": status.get("cancelled"),
        "awarded": status.get("awarded"),
        "score_str": status.get("scoreStr"),
        "result_reason": status.get("reason", {}).get("long")
    })

matches_clean = pd.DataFrame(match_rows)

print("Total matches:", len(matches_clean))
matches_clean.head()

Total matches: 104

,match_id,match_name,round,home_team_id,home_team,home_score,home_fifa_rank,away_team_id,away_team,away_score,away_fifa_rank,match_time_utc,started,finished,cancelled,awarded,score_str,result_reason
0,4653703,"Germany-vs-Paraguay_Mon, Jun 29, 2026, 20:30 UTC",1/16,8570,Germany,1,10,6724,Paraguay,1,41,2026-06-29T20:30:00.000Z,True,True,False,False,1 - 1,Pen 3 - 4
1,4653704,"France-vs-Sweden_Tue, Jun 30, 2026, 21:00 UTC",1/16,6723,France,3,3,8520,Sweden,0,38,2026-06-30T21:00:00.000Z,True,True,False,False,3 - 0,Full-Time
2,4653705,"South Africa-vs-Canada_Sun, Jun 28, 2026, 19:0...",1/16,6316,South Africa,0,60,5810,Canada,1,30,2026-06-28T19:00:00.000Z,True,True,False,False,0 - 1,Full-Time
3,4653706,"Netherlands-vs-Morocco_Tue, Jun 30, 2026, 01:0...",1/16,6708,Netherlands,1,8,6262,Morocco,1,7,2026-06-30T01:00:00.000Z,True,True,False,False,1 - 1,Pen 2 - 3
4,4653707,"Portugal-vs-Croatia_Thu, Jul 2, 2026, 23:00 UTC",1/16,8361,Portugal,2,5,10155,Croatia,1,11,2026-07-02T23:00:00.000Z,True,True,False,False,2 - 1,Full-Time

In [53]:
#fixing data type
matches_clean["match_id"] = pd.to_numeric(
    matches_clean["match_id"],
    errors="coerce"
).astype("Int64")

matches_clean["home_team_id"] = pd.to_numeric(
    matches_clean["home_team_id"],
    errors="coerce"
).astype("Int64")

matches_clean["away_team_id"] = pd.to_numeric(
    matches_clean["away_team_id"],
    errors="coerce"
).astype("Int64")

matches_clean["home_score"] = pd.to_numeric(
    matches_clean["home_score"],
    errors="coerce"
)

matches_clean["away_score"] = pd.to_numeric(
    matches_clean["away_score"],
    errors="coerce"
)

matches_clean["match_time_utc"] = pd.to_datetime(
    matches_clean["match_time_utc"],
    errors="coerce",
    utc=True
)

In [54]:
#checking duplicates
print(
    "Duplicate match IDs:",
    matches_clean["match_id"].duplicated().sum()
)

Duplicate match IDs: 0

In [55]:
#creating match result
matches_clean["result"] = matches_clean.apply(
    lambda row: (
        "Draw"
        if row["home_score"] == row["away_score"]
        else "Home Win"
        if row["home_score"] > row["away_score"]
        else "Away Win"
    ),
    axis=1
)

In [56]:
#checking
matches_clean[
    [
        "match_id",
        "home_team",
        "home_score",
        "away_team",
        "away_score",
        "result"
    ]
].head(10)

,match_id,home_team,home_score,away_team,away_score,result
0,4653703,Germany,1,Paraguay,1,Draw
1,4653704,France,3,Sweden,0,Home Win
2,4653705,South Africa,0,Canada,1,Away Win
3,4653706,Netherlands,1,Morocco,1,Draw
4,4653707,Portugal,2,Croatia,1,Home Win
5,4653708,Spain,3,Austria,0,Home Win
6,4653709,USA,2,Bosnia and Herzegovina,0,Home Win
7,4653710,Belgium,3,Senegal,2,Home Win
8,4653711,Brazil,2,Japan,1,Home Win
9,4653712,Ivory Coast,1,Norway,2,Away Win

In [57]:
os.makedirs("data/processed", exist_ok=True)

matches_clean.to_csv(
    "data/processed/matches_clean.csv",
    index=False
)

print("matches_clean.csv saved")

matches_clean.csv saved

In [58]:
player_ids = set(players_clean["player_id"].astype(str))

print("Players to find:", len(player_ids))

Players to find: 1243

In [59]:
def find_players(obj, player_ids, results=None):
    if results is None:
        results = []

    if isinstance(obj, dict):
        # Check whether this dictionary represents a player
        possible_id = (
            obj.get("id")
            or obj.get("playerId")
            or obj.get("player_id")
        )

        if possible_id is not None and str(possible_id) in player_ids:
            results.append(obj)

        for value in obj.values():
            find_players(value, player_ids, results)

    elif isinstance(obj, list):
        for item in obj:
            find_players(item, player_ids, results)

    return results

In [60]:
team_json_path = "data/raw/teams"

detailed_players = []

for filename in os.listdir(team_json_path):

    if not filename.endswith(".json"):
        continue

    filepath = os.path.join(team_json_path, filename)

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    found = find_players(data, player_ids)

    detailed_players.extend(found)

print("Detailed player records found:", len(detailed_players))

Detailed player records found: 6622

In [61]:
#converting into data framee
detailed_players_df = pd.json_normalize(detailed_players)

print("Shape:", detailed_players_df.shape)

detailed_players_df.head()

Shape: (6622, 63)

,id,age,name,positionId,usualPlayingPositionId,shirtNumber,countryName,countryCode,primaryTeamId,primaryTeamName,...,performance.seasonRating,performance.seasonAssists,unavailability.injuryId,unavailability.type,unavailability.expectedReturn,injured,injury.id,injury.expectedReturn,unavailability.expectedReturnDate,performance.playerOfTheMatch
0,466867,30.0,Nikola Vasilj,11.0,0.0,1,Bosnia and Herzegovina,BIH,8152.0,St. Pauli,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,725655,29.0,Nikola Katic,33.0,1.0,18,Bosnia and Herzegovina,BIH,10189.0,Schalke 04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1250485,23.0,Tarik Muharemovic,35.0,1.0,4,Bosnia and Herzegovina,BIH,7943.0,Sassuolo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,653982,28.0,Stjepan Radeljic,37.0,1.0,21,Bosnia and Herzegovina,BIH,10156.0,Dinamo Zagreb,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,958010,23.0,Amar Dedic,51.0,1.0,7,Bosnia and Herzegovina,BIH,9772.0,Benfica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
print(detailed_players_df.columns.tolist())

['id', 'age', 'name', 'positionId', 'usualPlayingPositionId', 'shirtNumber', 'countryName', 'countryCode', 'primaryTeamId', 'primaryTeamName', 'marketValue', 'horizontalLayout.x', 'horizontalLayout.y', 'horizontalLayout.height', 'horizontalLayout.width', 'verticalLayout.x', 'verticalLayout.y', 'verticalLayout.height', 'verticalLayout.width', 'performance.rating', 'performance.substitutionEvents', 'performance.events', 'isCaptain', 'ccode', 'cname', 'injury', 'rating', 'goals', 'penalties', 'assists', 'rcards', 'ycards', 'excludeFromRanking', 'positionIds', 'positionIdsDesc', 'height', 'dateOfBirth', 'transferValue', 'role.key', 'role.fallback', 'performance.seasonGoals', 'rank', 'teamId', 'teamName', 'value', 'stat.name', 'stat.value', 'stat.format', 'stat.fractions', 'teamColors.darkMode', 'teamColors.lightMode', 'teamColors.fontDarkMode', 'teamColors.fontLightMode', 'performance.seasonRating', 'performance.seasonAssists', 'unavailability.injuryId', 'unavailability.type', 'unavailability.expectedReturn', 'injured', 'injury.id', 'injury.expectedReturn', 'unavailability.expectedReturnDate', 'performance.playerOfTheMatch']

In [63]:
detail_columns = [
    "id",
    "age",
    "name",
    "positionId",
    "usualPlayingPositionId",
    "shirtNumber",
    "marketValue",
    "rating",
    "goals",
    "assists",
    "rcards",
    "ycards",
    "height",
    "dateOfBirth",
    "transferValue",
    "performance.seasonGoals",
    "performance.seasonRating",
    "performance.seasonAssists",
    "performance.playerOfTheMatch",
    "isCaptain"
]

player_details = detailed_players_df[
    [c for c in detail_columns if c in detailed_players_df.columns]
].copy()

In [64]:
player_details["player_id"] = pd.to_numeric(
    player_details["id"],
    errors="coerce"
).astype("Int64")

player_details = player_details.drop(columns=["id"])

In [65]:
player_details = player_details.rename(columns={
    "name": "detail_name",
    "marketValue": "market_value_eur",
    "rcards": "red_cards",
    "ycards": "yellow_cards",
    "height": "detail_height_cm",
    "dateOfBirth": "detail_birth_date",
    "transferValue": "detail_transfer_value_eur",
    "performance.seasonGoals": "season_goals",
    "performance.seasonRating": "season_rating",
    "performance.seasonAssists": "season_assists",
    "performance.playerOfTheMatch": "player_of_the_match"
})

In [66]:
players_full = players_clean.merge(
    player_details,
    on="player_id",
    how="left"
)

print("Player lookup:", players_clean.shape)
print("Detailed data:", player_details.shape)
print("Final dataset:", players_full.shape)

Player lookup: (1243, 11)
Detailed data: (6622, 20)
Final dataset: (6622, 30)

In [67]:
print(
    "Players with detailed data:",
    players_full["detail_name"].notna().sum()
)

print(
    "Players without detailed data:",
    players_full["detail_name"].isna().sum()
)

Players with detailed data: 6622
Players without detailed data: 0

In [68]:
players_full.to_csv(
    "data/processed/players_full.csv",
    index=False
)

print("players_full.csv saved successfully!")

players_full.csv saved successfully!

In [70]:
players_full[
    [
        "player_id",
        "player_name",
        "country",
        "primary_position",
        "club_name",
        "rating",
        "goals",
        "assists",
        "season_rating"
    ]
].head(100)

,player_id,player_name,country,primary_position,club_name,rating,goals,assists,season_rating
0,1057426,Armin Gigovic,Bosnia and Herzegovina,defensive midfielder,Young Boys,NaN,NaN,NaN,NaN
1,1057426,Armin Gigovic,Bosnia and Herzegovina,defensive midfielder,Young Boys,NaN,0.0,0.0,NaN
2,1057426,Armin Gigovic,Bosnia and Herzegovina,defensive midfielder,Young Boys,NaN,0.0,0.0,NaN
3,1174844,Jovo Lukic,Bosnia and Herzegovina,striker,Universitatea Cluj,NaN,NaN,NaN,NaN
4,1174844,Jovo Lukic,Bosnia and Herzegovina,striker,Universitatea Cluj,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
95,1215064,Martin Baturina,Croatia,left winger,Como,NaN,0.0,0.0,NaN
96,1300358,Toni Fruk,Croatia,attacking midfielder,Rijeka,NaN,NaN,NaN,NaN
97,1300358,Toni Fruk,Croatia,attacking midfielder,Rijeka,NaN,0.0,0.0,NaN
98,1300358,Toni Fruk,Croatia,attacking midfielder,Rijeka,NaN,0.0,0.0,NaN
99,1382000,Petar Sucic,Croatia,central midfielder,Inter,NaN,NaN,NaN,NaN

In [71]:
players_full.shape

(6622, 30)

In [72]:
print("Total rows:", len(players_full))
print("Unique player IDs:", players_full["player_id"].nunique())

Total rows: 6622
Unique player IDs: 1243

In [73]:
duplicate_counts = (
    players_full
    .groupby("player_id")
    .size()
    .sort_values(ascending=False)
)

duplicate_counts.head(10)

player_id
30981      41
701154     34
278343     33
846033     33
1615927    31
1059490    30
666857     30
771294     29
1073742    28
720560     28
dtype: int64

In [74]:
player_details_clean = (
    player_details
    .drop_duplicates(subset=["player_id"])
    .copy()
)

print("Detailed records:", len(player_details_clean))
print("Unique player IDs:", player_details_clean["player_id"].nunique())

Detailed records: 1243
Unique player IDs: 1243

In [75]:
players_full = players_clean.merge(
    player_details_clean,
    on="player_id",
    how="left"
)

print("Final rows:", len(players_full))
print("Unique player IDs:", players_full["player_id"].nunique())

Final rows: 1243
Unique player IDs: 1243

In [76]:
print("Duplicate player IDs:",
      players_full["player_id"].duplicated().sum())

Duplicate player IDs: 0

In [77]:
players_full[
    [
        "player_id",
        "player_name",
        "country",
        "primary_position",
        "club_name",
        "rating",
        "goals",
        "assists"
    ]
].head(10)

,player_id,player_name,country,primary_position,club_name,rating,goals,assists
0,1057426,Armin Gigovic,Bosnia and Herzegovina,defensive midfielder,Young Boys,NaN,NaN,NaN
1,1174844,Jovo Lukic,Bosnia and Herzegovina,striker,Universitatea Cluj,NaN,NaN,NaN
2,1179875,Ivan Basic,Bosnia and Herzegovina,central midfielder,FC Astana,NaN,NaN,NaN
3,1250485,Tarik Muharemovic,Bosnia and Herzegovina,center back,Leeds United,NaN,NaN,NaN
4,1284492,Samed Bazdar,Bosnia and Herzegovina,striker,Real Zaragoza,NaN,NaN,NaN
5,1300385,Amar Memic,Bosnia and Herzegovina,right wing-back,Viktoria Plzen,NaN,NaN,NaN
6,1346860,Esmir Bajraktarevic,Bosnia and Herzegovina,right winger,PSV Eindhoven,NaN,NaN,NaN
7,1415104,Benjamin Tahirovic,Bosnia and Herzegovina,central midfielder,Brøndby IF,NaN,NaN,NaN
8,1515122,Arjan Malic,Bosnia and Herzegovina,right back,Sturm Graz,NaN,NaN,NaN
9,1528815,Ermin Mahmic,Bosnia and Herzegovina,attacking midfielder,Slovan Liberec,NaN,NaN,NaN

In [78]:
players_full.to_csv(
    "data/processed/players_full.csv",
    index=False
)

print("Clean player dataset saved!")

Clean player dataset saved!